
- name: up docker services
  docker_service:
    project_src: "{{ base_dir }}"
    files:
      - production.yml
    build: no
    pull: yes
    restarted: true
  register: output

- debug:
    var: output
